# Generated by Django 4.1.4 on 2022-12-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0003_alter_addon_image_url_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='image_url',
        ),
    ]
