# Generated by Django 4.1.4 on 2022-12-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0004_remove_addon_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kiosk_Product',
            new_name='Selected_Product',
        ),
    ]
