# Generated by Django 4.1.4 on 2022-12-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0005_rename_kiosk_product_selected_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_product',
            name='kiosk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='ordering_app.kiosk'),
        ),
    ]
