# Generated by Django 4.1.4 on 2022-12-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0006_alter_selected_product_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kiosk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordering_app.kiosk'),
        ),
    ]
