# Generated by Django 4.1.4 on 2022-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0007_alter_order_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='queue_number',
            field=models.CharField(max_length=50),
        ),
    ]
